-- ================================================================
-- ESQUEMA BASE (sin datos) — Vincúlate SEDECO
-- Derivado del SQL maestro 2026-09-21 (v5): secciones 1 a 5 y 7, SIN los
-- INSERT de personas/vacantes/vinculaciones (esos datos personales NO se
-- versionan en GitHub; cárgalos desde la app con "Cargas" o desde tus CSV).
--
-- Úsalo SOLO para crear un proyecto Supabase NUEVO (pruebas o producción
-- limpia). Después ejecuta supabase/migrations/V001... en orden.
-- Si ya tienes el proyecto vivo con el SQL maestro, NO lo ejecutes de nuevo:
-- ve directo a las migraciones.
-- ================================================================
set datestyle = 'ISO, DMY';
create extension if not exists pgcrypto with schema extensions;

-- 1) DATOS OPERATIVOS
create table if not exists public.personas (
 id_persona text primary key, id_persona_maestro text not null, nombre text not null,
 sexo text, edad integer, escolaridad text, carrera text, institucion text,
 id_institucion text, municipio text, id_municipio text, telefono text, correo text,
 grupo_prioritario text, vinculacion text, fecha_registro date, anio integer,
 area_carrera text, estatus_vinculacion text, actualizado_en timestamptz not null default now()
);
create index if not exists idx_personas_maestro on public.personas(id_persona_maestro);
create index if not exists idx_personas_anio on public.personas(anio);
create index if not exists idx_personas_vinculacion on public.personas(vinculacion);

create table if not exists public.vacantes (
 id_vacante text primary key, id_registro_origen text, actividad text, fecha date,
 empresa text, sector_empresa text, puesto_original text, tipo_vacante text,
 categoria_puesto text, tipo_oportunidad text, area_oportunidad text, descripcion text,
 requisitos text, beneficios text, link_publicacion text, estado text,
 actualizado_en timestamptz not null default now()
);
create index if not exists idx_vacantes_empresa on public.vacantes(empresa);
create index if not exists idx_vacantes_fecha on public.vacantes(fecha);

create table if not exists public.vinculaciones (
 id_vinculacion text primary key, id_persona_maestro text not null,
 id_registro_origen text, nombre_persona text, empresa text, sector_empresa text,
 tipo_vacante text, area_oportunidad text, estatus text, fecha_vinculacion date,
 fecha_colocacion date, observaciones text, responsable text, fecha_actualizacion text,
 actualizado_en timestamptz not null default now(),
 constraint vinculaciones_estatus_check check (estatus is null or estatus in ('Vinculado','Colocado','No vinculado'))
);
create index if not exists idx_vinc_maestro on public.vinculaciones(id_persona_maestro);
create index if not exists idx_vinc_estatus on public.vinculaciones(estatus);
create index if not exists idx_vinc_fecha_colocacion on public.vinculaciones(fecha_colocacion);

create table if not exists public.historial_cargas (
 id bigint generated by default as identity primary key, fecha_hora text, usuario text,
 base text, origen text, archivo_origen text, registros_recibidos integer,
 registros_guardados integer, duplicados_actualizados integer, total_final integer,
 creado_en timestamptz not null default now(),
 hash_evento text generated always as (md5(coalesce(fecha_hora,'')||'|'||coalesce(usuario,'')||'|'||coalesce(base,'')||'|'||coalesce(origen,'')||'|'||coalesce(archivo_origen,'')||'|'||coalesce(registros_recibidos::text,'')||'|'||coalesce(total_final::text,''))) stored unique
);

create table if not exists public.catalogo_instituciones (nombre text primary key, activo boolean not null default true);
create table if not exists public.catalogo_carreras (nombre text primary key, activo boolean not null default true);
create table if not exists public.catalogo_municipios_tlaxcala (nombre text primary key, activo boolean not null default true);
create table if not exists public.catalogo_empresas (nombre text primary key, sector text, activo boolean not null default true);

-- 2) ADMINISTRACIÓN V5
create table if not exists public.app_profiles (
 user_id uuid primary key references auth.users(id) on delete cascade,
 email text not null, display_name text not null,
 role text not null default 'collaborator' check (role in ('admin','collaborator')),
 status text not null default 'pending' check (status in ('pending','active','disabled')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists app_profiles_email_lower_uidx on public.app_profiles(lower(email));

create table if not exists public.app_permissions (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.app_profiles(user_id) on delete cascade,
 module_key text not null,
 can_view boolean not null default false, can_create boolean not null default false,
 can_edit boolean not null default false, can_delete boolean not null default false,
 can_export boolean not null default false, updated_at timestamptz not null default now(),
 constraint app_permissions_module_check check (module_key in ('inicio','personas','vacantes','vinculaciones','explorador','ridet','administracion','usuarios','dispositivos','prioridades','auditoria','respaldos')),
 unique(user_id,module_key)
);

create table if not exists public.app_devices (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.app_profiles(user_id) on delete cascade,
 device_id text not null, hostname text, os_name text, os_version text, app_version text,
 authorized boolean not null default false, created_at timestamptz not null default now(),
 last_seen timestamptz not null default now(), unique(user_id,device_id)
);
create index if not exists idx_app_devices_user on public.app_devices(user_id);

create table if not exists public.app_audit_log (
 id bigint generated by default as identity primary key,
 user_id uuid references public.app_profiles(user_id) on delete set null,
 email text, action text not null, detail text, device_id text,
 created_at timestamptz not null default now()
);
create index if not exists idx_app_audit_created on public.app_audit_log(created_at desc);
create index if not exists idx_app_audit_user on public.app_audit_log(user_id);

create table if not exists public.app_priorities (
 id bigint generated by default as identity primary key,
 entity_type text not null, entity_id text not null, title text not null,
 description text, priority_level text not null default 'normal' check(priority_level in ('normal','alta','urgente')),
 reminder_at timestamptz, repeat_minutes integer not null default 60 check(repeat_minutes>=1),
 active boolean not null default true, created_by uuid references public.app_profiles(user_id) on delete set null,
 created_at timestamptz not null default now(), completed_at timestamptz
);

create table if not exists public.app_priority_notifications (
 priority_id bigint not null references public.app_priorities(id) on delete cascade,
 user_id uuid not null references public.app_profiles(user_id) on delete cascade,
 last_seen_at timestamptz not null default now(), primary key(priority_id,user_id)
);

-- 3) FUNCIONES DE AUTORIZACIÓN
create or replace function public.is_active_user() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.app_profiles where user_id=auth.uid() and status='active');
$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.app_profiles where user_id=auth.uid() and role='admin' and status='active');
$$;
create or replace function public.has_permission(p_module text,p_action text default 'view') returns boolean language sql stable security definer set search_path=public as $$
 select public.is_admin() or exists(select 1 from public.app_permissions p join public.app_profiles u on u.user_id=p.user_id where p.user_id=auth.uid() and u.status='active' and p.module_key=p_module and case p_action when 'view' then p.can_view when 'create' then p.can_create when 'edit' then p.can_edit when 'delete' then p.can_delete when 'export' then p.can_export else false end);
$$;

-- 4) RLS
alter table public.personas enable row level security;
alter table public.vacantes enable row level security;
alter table public.vinculaciones enable row level security;
alter table public.historial_cargas enable row level security;
alter table public.catalogo_instituciones enable row level security;
alter table public.catalogo_carreras enable row level security;
alter table public.catalogo_municipios_tlaxcala enable row level security;
alter table public.catalogo_empresas enable row level security;
alter table public.app_profiles enable row level security;
alter table public.app_permissions enable row level security;
alter table public.app_devices enable row level security;
alter table public.app_audit_log enable row level security;
alter table public.app_priorities enable row level security;
alter table public.app_priority_notifications enable row level security;

-- Ping de nube de la v5 antes del login: solo lectura mínima de personas para anon.
grant select on public.personas to anon;
drop policy if exists personas_anon_ping on public.personas;
create policy personas_anon_ping on public.personas for select to anon using (true);

-- Datos operativos: solo usuarios activos; permisos por módulo.
grant select,insert,update,delete on public.personas,public.vacantes,public.vinculaciones,public.historial_cargas,public.catalogo_instituciones,public.catalogo_carreras,public.catalogo_municipios_tlaxcala,public.catalogo_empresas to authenticated;

do $$ declare t text; begin
 foreach t in array array['personas','vacantes','vinculaciones','historial_cargas','catalogo_instituciones','catalogo_carreras','catalogo_municipios_tlaxcala','catalogo_empresas'] loop
  execute format('drop policy if exists %I on public.%I',t||'_auth_all',t);
  execute format('create policy %I on public.%I for all to authenticated using (public.is_active_user()) with check (public.is_active_user())',t||'_auth_all',t);
 end loop;
end $$;

-- Perfiles
create policy profiles_select on public.app_profiles for select to authenticated using(user_id=auth.uid() or public.is_admin() or public.has_permission('usuarios','view'));
create policy profiles_insert on public.app_profiles for insert to authenticated with check(public.is_admin() or public.has_permission('usuarios','create'));
create policy profiles_update on public.app_profiles for update to authenticated using(public.is_admin() or public.has_permission('usuarios','edit')) with check(public.is_admin() or public.has_permission('usuarios','edit'));
create policy profiles_delete on public.app_profiles for delete to authenticated using(public.is_admin() or public.has_permission('usuarios','delete'));

-- Permisos
create policy permissions_select on public.app_permissions for select to authenticated using(user_id=auth.uid() or public.is_admin() or public.has_permission('usuarios','view'));
create policy permissions_insert on public.app_permissions for insert to authenticated with check(public.is_admin() or public.has_permission('usuarios','edit'));
create policy permissions_update on public.app_permissions for update to authenticated using(public.is_admin() or public.has_permission('usuarios','edit')) with check(public.is_admin() or public.has_permission('usuarios','edit'));
create policy permissions_delete on public.app_permissions for delete to authenticated using(public.is_admin() or public.has_permission('usuarios','delete'));

-- Equipos: cada usuario puede registrar su propio equipo pendiente; admin gestiona.
create policy devices_select on public.app_devices for select to authenticated using(user_id=auth.uid() or public.is_admin() or public.has_permission('dispositivos','view'));
create policy devices_insert on public.app_devices for insert to authenticated with check(user_id=auth.uid() and public.is_active_user());
create policy devices_update on public.app_devices for update to authenticated using((user_id=auth.uid() and authorized=true and public.is_active_user()) or public.is_admin() or public.has_permission('dispositivos','edit')) with check((user_id=auth.uid() and authorized=true and public.is_active_user()) or public.is_admin() or public.has_permission('dispositivos','edit'));
create policy devices_delete on public.app_devices for delete to authenticated using(public.is_admin() or public.has_permission('dispositivos','delete'));

-- Auditoría
create policy audit_insert on public.app_audit_log for insert to authenticated with check(user_id=auth.uid());
create policy audit_select on public.app_audit_log for select to authenticated using(public.is_admin() or public.has_permission('auditoria','view'));

-- Prioridades
create policy priorities_select on public.app_priorities for select to authenticated using(public.is_active_user() and (public.is_admin() or public.has_permission('prioridades','view')));
create policy priorities_insert on public.app_priorities for insert to authenticated with check(created_by=auth.uid() and (public.is_admin() or public.has_permission('prioridades','create')));
create policy priorities_update on public.app_priorities for update to authenticated using(public.is_admin() or public.has_permission('prioridades','edit')) with check(public.is_admin() or public.has_permission('prioridades','edit'));
create policy priorities_delete on public.app_priorities for delete to authenticated using(public.is_admin() or public.has_permission('prioridades','delete'));
create policy notifications_select on public.app_priority_notifications for select to authenticated using(user_id=auth.uid());
create policy notifications_insert on public.app_priority_notifications for insert to authenticated with check(user_id=auth.uid());
create policy notifications_update on public.app_priority_notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

-- Grants administrativos
grant select,insert,update,delete on public.app_profiles,public.app_permissions,public.app_devices,public.app_priorities to authenticated;
grant select,insert on public.app_audit_log to authenticated;
grant select,insert,update on public.app_priority_notifications to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- 5) RPC V5 DE USUARIOS
create or replace function public.admin_finalize_collaborator(p_email text,p_new_password text,p_display_name text) returns uuid language plpgsql security definer set search_path=public,auth,extensions as $$
declare v_email text:=lower(trim(coalesce(p_email,''))); v_uid uuid; v_name text:=trim(coalesce(p_display_name,''));
begin
 if not(public.is_admin() or public.has_permission('usuarios','create')) then raise exception 'No autorizado para crear usuarios'; end if;
 if v_email='' or position('@' in v_email)<=1 then raise exception 'Correo electrónico inválido'; end if;
 if p_new_password is null or length(p_new_password)<8 or length(p_new_password)>72 then raise exception 'La contraseña debe tener entre 8 y 72 caracteres'; end if;
 select id into v_uid from auth.users where lower(email)=v_email order by created_at desc limit 1;
 if v_uid is null then raise exception 'El usuario todavía no existe en Supabase Authentication. Reintenta el alta.'; end if;
 if v_name='' then v_name:=v_email; end if;
 if exists(select 1 from public.app_profiles where lower(email)=v_email and user_id<>v_uid) then raise exception 'Existe un perfil duplicado con este correo.'; end if;
 update auth.users set encrypted_password=extensions.crypt(p_new_password,extensions.gen_salt('bf')),email_confirmed_at=coalesce(email_confirmed_at,now()),raw_user_meta_data=coalesce(raw_user_meta_data,'{}'::jsonb)||jsonb_build_object('display_name',v_name),updated_at=now() where id=v_uid;
 insert into public.app_profiles(user_id,email,display_name,role,status) values(v_uid,v_email,v_name,'collaborator','active') on conflict(user_id) do update set email=excluded.email,display_name=excluded.display_name,role=case when public.app_profiles.role='admin' then 'admin' else 'collaborator' end,status='active',updated_at=now();
 insert into public.app_permissions(user_id,module_key,can_view,can_create,can_edit,can_delete,can_export,updated_at)
 select v_uid,m,(m='inicio'),false,false,false,false,now() from unnest(array['inicio','personas','vacantes','vinculaciones','explorador','ridet','administracion','usuarios','dispositivos','prioridades','auditoria','respaldos']) m on conflict(user_id,module_key) do nothing;
 return v_uid;
end $$;

create or replace function public.admin_replace_user_permissions(p_user_id uuid,p_permissions jsonb) returns void language plpgsql security definer set search_path=public as $$
declare item jsonb; mk text; cv boolean;
begin
 if not(public.is_admin() or public.has_permission('usuarios','edit')) then raise exception 'No autorizado para modificar permisos'; end if;
 if not exists(select 1 from public.app_profiles where user_id=p_user_id) then raise exception 'El perfil indicado no existe'; end if;
 if exists(select 1 from public.app_profiles where user_id=p_user_id and role='admin') then raise exception 'La matriz de un administrador no se modifica desde esta operación'; end if;
 if jsonb_typeof(p_permissions)<>'array' then raise exception 'Formato de permisos inválido'; end if;
 delete from public.app_permissions where user_id=p_user_id;
 for item in select value from jsonb_array_elements(p_permissions) loop
  mk:=trim(coalesce(item->>'module_key','')); if mk<>all(array['inicio','personas','vacantes','vinculaciones','explorador','ridet','administracion','usuarios','dispositivos','prioridades','auditoria','respaldos']) then continue; end if;
  cv:=coalesce((item->>'can_view')::boolean,false);
  insert into public.app_permissions(user_id,module_key,can_view,can_create,can_edit,can_delete,can_export,updated_at) values(p_user_id,mk,cv,cv and coalesce((item->>'can_create')::boolean,false),cv and coalesce((item->>'can_edit')::boolean,false),cv and coalesce((item->>'can_delete')::boolean,false),cv and coalesce((item->>'can_export')::boolean,false),now());
 end loop;
end $$;

create or replace function public.admin_set_user_password(p_user_id uuid,p_new_password text) returns void language plpgsql security definer set search_path=public,auth,extensions as $$
begin
 if not(public.is_admin() or public.has_permission('usuarios','edit')) then raise exception 'No autorizado'; end if;
 if p_new_password is null or length(p_new_password)<8 or length(p_new_password)>72 then raise exception 'La contraseña debe tener entre 8 y 72 caracteres'; end if;
 update auth.users set encrypted_password=extensions.crypt(p_new_password,extensions.gen_salt('bf')),email_confirmed_at=coalesce(email_confirmed_at,now()),updated_at=now() where id=p_user_id;
 if not found then raise exception 'Usuario no encontrado'; end if;
end $$;

create or replace function public.admin_update_user_account(p_user_id uuid,p_email text,p_display_name text,p_role text,p_status text) returns void language plpgsql security definer set search_path=public,auth,extensions as $$
declare v_email text:=lower(trim(coalesce(p_email,''))); v_name text:=trim(coalesce(p_display_name,''));
begin
 if not(public.is_admin() or public.has_permission('usuarios','edit')) then raise exception 'No autorizado para modificar cuentas'; end if;
 if v_email='' or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'Correo electrónico inválido'; end if;
 if p_role not in('admin','collaborator') then raise exception 'Rol inválido'; end if; if p_status not in('pending','active','disabled') then raise exception 'Estado inválido'; end if; if v_name='' then v_name:=v_email; end if;
 if exists(select 1 from auth.users where lower(email)=v_email and id<>p_user_id) or exists(select 1 from public.app_profiles where lower(email)=v_email and user_id<>p_user_id) then raise exception 'Ese correo ya pertenece a otra cuenta'; end if;
 if exists(select 1 from public.app_profiles where user_id=p_user_id and role='admin' and status='active') and (p_role<>'admin' or p_status<>'active') and (select count(*) from public.app_profiles where role='admin' and status='active')<=1 then raise exception 'No se puede desactivar o degradar al último administrador activo'; end if;
 update auth.users set email=v_email,email_confirmed_at=coalesce(email_confirmed_at,now()),raw_user_meta_data=coalesce(raw_user_meta_data,'{}'::jsonb)||jsonb_build_object('display_name',v_name),updated_at=now() where id=p_user_id; if not found then raise exception 'Usuario no encontrado en Authentication'; end if;
 update auth.identities set identity_data=coalesce(identity_data,'{}'::jsonb)||jsonb_build_object('email',v_email),updated_at=now() where user_id=p_user_id and provider='email';
 update public.app_profiles set email=v_email,display_name=v_name,role=p_role,status=p_status,updated_at=now() where user_id=p_user_id; if not found then raise exception 'Perfil Vincúlate no encontrado'; end if;
 if p_status='disabled' then update public.app_devices set authorized=false where user_id=p_user_id; end if;
end $$;

create or replace function public.admin_delete_user_account(p_user_id uuid) returns void language plpgsql security definer set search_path=public,auth as $$
begin
 if not(public.is_admin() or public.has_permission('usuarios','delete')) then raise exception 'No autorizado para eliminar cuentas'; end if;
 if p_user_id=auth.uid() then raise exception 'No puedes eliminar tu propia cuenta durante una sesión activa'; end if;
 if not exists(select 1 from public.app_profiles where user_id=p_user_id) then raise exception 'Perfil no encontrado'; end if;
 if exists(select 1 from public.app_profiles where user_id=p_user_id and role='admin' and status='active') and (select count(*) from public.app_profiles where role='admin' and status='active')<=1 then raise exception 'No se puede eliminar al último administrador activo'; end if;
 delete from public.app_priority_notifications where user_id=p_user_id; delete from public.app_priorities where created_by=p_user_id; delete from public.app_audit_log where user_id=p_user_id; delete from public.app_permissions where user_id=p_user_id; delete from public.app_devices where user_id=p_user_id; delete from public.app_profiles where user_id=p_user_id; delete from auth.users where id=p_user_id;
end $$;

revoke all on function public.admin_finalize_collaborator(text,text,text) from public;
revoke all on function public.admin_replace_user_permissions(uuid,jsonb) from public;
revoke all on function public.admin_set_user_password(uuid,text) from public;
revoke all on function public.admin_update_user_account(uuid,text,text,text,text) from public;
revoke all on function public.admin_delete_user_account(uuid) from public;
grant execute on function public.admin_finalize_collaborator(text,text,text),public.admin_replace_user_permissions(uuid,jsonb),public.admin_set_user_password(uuid,text),public.admin_update_user_account(uuid,text,text,text,text),public.admin_delete_user_account(uuid) to authenticated;


-- 7) FUNCIÓN DE ARRANQUE DEL PRIMER ADMINISTRADOR
-- Después de crear TU usuario en Authentication, inicia sesión y ejecuta por RPC
-- bootstrap_first_admin() una sola vez, o usa el bloque manual indicado al final.
create or replace function public.bootstrap_first_admin() returns void language plpgsql security definer set search_path=public,auth as $$
declare v_email text; v_name text;
begin
 if auth.uid() is null then raise exception 'Debes estar autenticado'; end if;
 if exists(select 1 from public.app_profiles) then raise exception 'El sistema ya tiene perfiles; bootstrap cerrado'; end if;
 select lower(email),coalesce(raw_user_meta_data->>'display_name',email) into v_email,v_name from auth.users where id=auth.uid();
 insert into public.app_profiles(user_id,email,display_name,role,status) values(auth.uid(),v_email,v_name,'admin','active');
 insert into public.app_permissions(user_id,module_key,can_view,can_create,can_edit,can_delete,can_export)
 select auth.uid(),m,true,true,true,true,true from unnest(array['inicio','personas','vacantes','vinculaciones','explorador','ridet','administracion','usuarios','dispositivos','prioridades','auditoria','respaldos']) m;
end $$;
revoke all on function public.bootstrap_first_admin() from public;
grant execute on function public.bootstrap_first_admin() to authenticated;
