-- Claves INEGI (CVE_MUN) de los 60 municipios de Tlaxcala. Requiere V004. Solo rellena donde cve_mun es NULL.
begin;
update public.catalogo_municipios_tlaxcala m set cve_mun = v.cve
from (values
  ('AMAXAC DE GUERRERO', '001'),
  ('APETATITLÁN DE ANTONIO CARVAJAL', '002'),
  ('ATLANGATEPEC', '003'),
  ('ALTZAYANCA', '004'),
  ('APIZACO', '005'),
  ('CALPULALPAN', '006'),
  ('EL CARMEN TEQUEXQUITLA', '007'),
  ('CUAPIAXTLA', '008'),
  ('CUAXOMULCO', '009'),
  ('CHIAUTEMPAN', '010'),
  ('MUÑOZ DE DOMINGO ARENAS', '011'),
  ('ESPAÑITA', '012'),
  ('HUAMANTLA', '013'),
  ('HUEYOTLIPAN', '014'),
  ('IXTACUIXTLA DE MARIANO MATAMOROS', '015'),
  ('IXTENCO', '016'),
  ('MAZATECOCHCO DE JOSÉ MARÍA MORELOS', '017'),
  ('CONTLA DE JUAN CUAMATZI', '018'),
  ('TEPETITLA DE LARDIZÁBAL', '019'),
  ('SANCTORUM DE LÁZARO CÁRDENAS', '020'),
  ('NANACAMILPA DE MARIANO ARISTA', '021'),
  ('ACUAMANALA DE MIGUEL HIDALGO', '022'),
  ('NATIVITAS', '023'),
  ('PANOTLA', '024'),
  ('SAN PABLO DEL MONTE', '025'),
  ('SANTA CRUZ TLAXCALA', '026'),
  ('TENANCINGO', '027'),
  ('TEOLOCHOLCO', '028'),
  ('TEPEYANCO', '029'),
  ('TERRENATE', '030'),
  ('TETLA DE LA SOLIDARIDAD', '031'),
  ('TETLATLAHUCA', '032'),
  ('TLAXCALA', '033'),
  ('TLAXCO', '034'),
  ('TOCATLÁN', '035'),
  ('TOTOLAC', '036'),
  ('ZITLALTEPEC DE TRINIDAD SÁNCHEZ SANTOS', '037'),
  ('TZOMPANTEPEC', '038'),
  ('XALOSTOC', '039'),
  ('XALTOCAN', '040'),
  ('PAPALOTLA DE XICOHTÉNCATL', '041'),
  ('XICOHTZINCO', '042'),
  ('YAUHQUEMECAN', '043'),
  ('ZACATELCO', '044'),
  ('BENITO JUÁREZ', '045'),
  ('EMILIANO ZAPATA', '046'),
  ('LÁZARO CÁRDENAS', '047'),
  ('LA MAGDALENA TLALTELULCO', '048'),
  ('SAN DAMIÁN TEXOLOC', '049'),
  ('SAN FRANCISCO TETLANOHCAN', '050'),
  ('SAN JERÓNIMO ZACUALPAN', '051'),
  ('SAN JOSÉ TEACALCO', '052'),
  ('SAN JUAN HUACTZINCO', '053'),
  ('SAN LORENZO AXOCOMANITLA', '054'),
  ('SAN LUCAS TECOPILCO', '055'),
  ('SANTA ANA NOPALUCAN', '056'),
  ('SANTA APOLONIA TEACALCO', '057'),
  ('SANTA CATARINA AYOMETLA', '058'),
  ('SANTA CRUZ QUILEHTLA', '059'),
  ('SANTA ISABEL XILOXOXTLA', '060')
) as v(nombre, cve)
where m.nombre = v.nombre and m.cve_mun is null;
-- Verificación: debe devolver 60 (o menos si el catálogo de tu base no tiene todos).
select count(*) as municipios_con_clave from public.catalogo_municipios_tlaxcala where cve_mun is not null;
commit;
